{{+
  const token = "opop"
  exports.defaultHeaders = {
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${token}`
  };
}}

@host=http://localhost:3000

###  Tunnels

# @name tunnels
GET /tunnels
...defaultHeaders


GET /tunnels/{{tunnels.records[0].id}}
...defaultHeaders

DELETE /tunnels/{{tunnels.records[0].id}}
...defaultHeaders


### Clients


# @name clients
GET /clients
...defaultHeaders

GET /clients/{{clients.records[0].id}}
...defaultHeaders

DELETE /clients/{{clients.records[0].id}}
...defaultHeaders

### Endpoints


# @name endpoints
GET /endpoints
...defaultHeaders

GET /endpoints/{{endpoints.records[1].name}}
...defaultHeaders

### System

GET /system/info
...defaultHeaders