{{+
  const token = "opop"
  exports.defaultHeaders = {
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${token}`
  };
}}

@host=http://localhost:3000

###  Tunnels

# @name tunnels
GET /tunnels
...defaultHeaders


GET /tunnels/{{tunnels.records[0].id}}
...defaultHeaders

DELETE /tunnels/{{tunnels.records[0].id}}
...defaultHeaders


### Links


# @name links
GET /links
...defaultHeaders

GET /links/{{links.records[0].id}}
...defaultHeaders

DELETE /links/{{links.records[0].id}}
...defaultHeaders



### System

GET /system/info
...defaultHeaders

### 
# @name endpoints
GET /system/endpoints
...defaultHeaders

# @ref endpoints
GET /system/endpoints/{{endpoints.records[0].name}}
...defaultHeaders

### 
# @name clients
GET /system/clients
...defaultHeaders

# @ref clients
GET /system/clients/{{clients.records[0].name}}
...defaultHeaders