{{+
  const token = "opop"
  exports.defaultHeaders = {
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${token}`
  };
}}

@host=http://localhost:3000

###  Tunnels

GET /tunnels
...defaultHeaders
  

